"""
Simulated identity provider with real per-user credentials.

Passwords are never stored in plaintext. Each user record in
data/users.json stores a random salt and a PBKDF2-HMAC-SHA256 hash of
their password (200,000 iterations), generated by scripts/create_user.py.
login() re-derives the hash from the supplied password + stored salt and
compares in constant time with hmac.compare_digest.

In production, swap this module for a real identity provider (Okta, Azure
AD, etc.) - the AuthenticatedUser / Role shape stays the same, so nothing
else in the app needs to change.
"""

import binascii
import hashlib
import hmac
import json
import os
from dataclasses import dataclass

from src.config import USERS_PATH
from src.rbac import ROLES, Role, get_role

PBKDF2_ITERATIONS = 200_000


@dataclass
class AuthenticatedUser:
    username: str
    full_name: str
    department: str
    role: Role


def hash_password(password: str, salt_hex: str) -> str:
    salt = binascii.unhexlify(salt_hex)
    dk = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, PBKDF2_ITERATIONS)
    return binascii.hexlify(dk).decode()


def hash_new_password(password: str):
    """Generates a fresh random salt and hash for a brand-new password."""
    salt = os.urandom(16)
    salt_hex = binascii.hexlify(salt).decode()
    return salt_hex, hash_password(password, salt_hex)


class UserDirectory:
    def __init__(self):
        with open(USERS_PATH, "r", encoding="utf-8") as f:
            self._users = json.load(f)

    def list_usernames(self):
        return list(self._users.keys())

    def list_users(self):
        """
        Returns user records safe to expose over an API - never includes
        password_salt or password_hash.
        """
        return [
            {
                "username": username,
                "full_name": rec["full_name"],
                "department": rec["department"],
                "role": rec["role"],
            }
            for username, rec in self._users.items()
        ]

    def add_user(self, username: str, full_name: str, department: str,
                 role: str, password: str):
        if username in self._users:
            raise ValueError(f"User '{username}' already exists.")
        if role not in ROLES:
            raise ValueError(f"Unknown role '{role}'. Must be one of {list(ROLES.keys())}.")
        if len(password) < 8:
            raise ValueError("Password must be at least 8 characters.")

        salt_hex, hash_hex = hash_new_password(password)
        self._users[username] = {
            "role": role,
            "full_name": full_name,
            "department": department,
            "password_salt": salt_hex,
            "password_hash": hash_hex,
        }
        self._save()

    def remove_user(self, username: str):
        if username not in self._users:
            raise KeyError(f"User '{username}' does not exist.")
        del self._users[username]
        self._save()

    def _save(self):
        with open(USERS_PATH, "w", encoding="utf-8") as f:
            json.dump(self._users, f, indent=2)

    def login(self, username: str, password: str) -> AuthenticatedUser:
        """
        Verifies username + password against the stored PBKDF2 hash.
        Raises PermissionError on any failure (unknown user OR wrong
        password) - the error message deliberately does not reveal which,
        to avoid leaking which usernames exist.
        """
        record = self._users.get(username)
        if record is None:
            raise PermissionError("Invalid username or password.")

        expected_hash = record["password_hash"]
        actual_hash = hash_password(password, record["password_salt"])

        if not hmac.compare_digest(expected_hash, actual_hash):
            raise PermissionError("Invalid username or password.")

        return AuthenticatedUser(
            username=username,
            full_name=record["full_name"],
            department=record["department"],
            role=get_role(record["role"]),
        )
